services:
  jenkins:
    user: root
    environment:
      KUBECONFIG: /var/jenkins_home/.kube/config
      KAFKA_JENKINS_K8S_HOST_REWRITE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/var/jenkins_home/.kube:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
