create table orders (
    id bigint generated by default as identity,
    order_number varchar(40) not null,
    user_email varchar(320) not null,
    status varchar(20) not null,
    payment_method varchar(30) not null,
    payment_tx_id varchar(60) not null,
    total_count integer not null,
    total_amount bigint not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_orders primary key (id)
);

create index idx_orders_user on orders (user_email);
create index idx_orders_number on orders (order_number);

create table order_items (
    id bigint generated by default as identity,
    order_id bigint not null,
    product_id varchar(100) not null,
    title varchar(500) not null,
    link varchar(1000),
    image varchar(1000),
    price bigint not null,
    quantity integer not null,
    mall_name varchar(200),
    brand varchar(200),
    constraint pk_order_items primary key (id),
    constraint fk_order_items_order foreign key (order_id) references orders (id) on delete cascade
);

create index idx_order_items_order on order_items (order_id);
