apiVersion: 1

datasources:
  - name: Kafka Talk Prometheus
    uid: kafka-talk-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Kafka Talk Tempo
    uid: kafka-talk-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        datasourceUid: kafka-talk-prometheus
