apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: kafka-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: kafka-discovery-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=65 -XX:InitialRAMPercentage=35
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 35
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 75
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: kafka-project
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
    - name: http
      port: 8761
      targetPort: 8761
