resources:
  - namespace.yaml
  - secrets.example.yaml
  - kafka.yaml
  - postgres.yaml
  - mongodb.yaml
  - redis.yaml
  - minio.yaml
  - elasticsearch.yaml
  - logstash.yaml
  - kibana.yaml
  - tempo.yaml
  - prometheus.yaml
  - grafana.yaml
  - auth-service.yaml
  - chat-service.yaml
  - shopping-service.yaml
  - autoscaling.yaml
  - news-service.yaml
  - frontend.yaml
