apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: kafka-project
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
    }

    filter {
      mutate {
        add_field => {
          "environment" => "local-k8s"
        }
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "kafka-talk-logs-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kafka-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
            - containerPort: 9600
          env:
            - name: LS_JAVA_OPTS
              value: -Xms256m -Xmx256m
          volumeMounts:
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: kafka-project
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - name: tcp-json
      port: 5000
      targetPort: 5000
    - name: monitoring
      port: 9600
      targetPort: 9600
