apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: kafka-project
type: Opaque
stringData:
  jwt-secret: change-this-local-kubernetes-secret-change-this
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: kafka-project
type: Opaque
stringData:
  root-user: kafka-talk
  root-password: kafka-talk-secret
