apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: kafka-project
type: Opaque
stringData:
  jwt-secret: change-this-local-kubernetes-secret-change-this
  openai-api-key: ""
  fcm-enabled: "false"
  fcm-project-id: ""
  fcm-service-account-json: ""
  fcm-dry-run: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: kafka-project
type: Opaque
stringData:
  root-user: kafka-talk
  root-password: kafka-talk-secret
