create table cart_items (
    id bigint generated by default as identity,
    user_email varchar(320) not null,
    product_id varchar(100) not null,
    title varchar(500) not null,
    link varchar(1000),
    image varchar(1000),
    price bigint not null,
    mall_name varchar(200),
    brand varchar(200),
    quantity integer not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_cart_items primary key (id),
    constraint uk_cart_items_user_product unique (user_email, product_id)
);

create index idx_cart_items_user on cart_items (user_email);
