server.port=8893
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=${SPRING_SHUTDOWN_TIMEOUT:30s}

spring.application.name=shopping-service

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
