input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "environment" => "${KAFKA_TALK_ENV:local}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
    index => "kafka-talk-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
