create table users (
    id bigint generated by default as identity,
    email varchar(255) not null,
    name varchar(255) not null,
    password_hash varchar(255),
    provider varchar(255) not null,
    provider_id varchar(255),
    role varchar(255) not null default 'USER',
    status_message varchar(500),
    profile_image_url varchar(1000),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    constraint pk_users primary key (id),
    constraint uk_users_email unique (email),
    constraint ck_users_provider check (provider in ('LOCAL', 'EMAIL', 'KAKAO')),
    constraint ck_users_role check (role in ('USER', 'ADMIN'))
);

create table email_codes (
    id bigint generated by default as identity,
    email varchar(255) not null,
    code varchar(255) not null,
    expires_at timestamp(6) with time zone not null,
    used boolean not null,
    constraint pk_email_codes primary key (id)
);

create table user_profile_history (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(255) not null,
    status_message varchar(500),
    profile_image_url varchar(1000),
    event_type varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_user_profile_history primary key (id)
);

create index idx_profile_history_user_created
    on user_profile_history (user_id, created_at);

create table admin_audit_events (
    id bigint generated by default as identity,
    actor_email varchar(320) not null,
    actor_name varchar(120) not null,
    action varchar(80) not null,
    resource_type varchar(80) not null,
    resource_id varchar(200) not null,
    summary varchar(500) not null,
    success boolean not null,
    details_json text not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_admin_audit_events primary key (id),
    constraint ck_admin_audit_events_action check (action in ('DLT_REPLAY_DRY_RUN', 'DLT_REPLAY_EXECUTE'))
);

create index idx_admin_audit_events_created_at
    on admin_audit_events (created_at);

create index idx_admin_audit_events_actor_action
    on admin_audit_events (actor_email, action);
