create table if not exists admin_audit_events (
    id bigint generated by default as identity,
    actor_email varchar(320) not null,
    actor_name varchar(120) not null,
    action varchar(80) not null,
    resource_type varchar(80) not null,
    resource_id varchar(200) not null,
    summary varchar(500) not null,
    success boolean not null,
    details_json text not null,
    created_at timestamp(6) with time zone not null,
    constraint pk_admin_audit_events primary key (id),
    constraint ck_admin_audit_events_action check (action in ('DLT_REPLAY_DRY_RUN', 'DLT_REPLAY_EXECUTE'))
);

create index if not exists idx_admin_audit_events_created_at
    on admin_audit_events (created_at);

create index if not exists idx_admin_audit_events_actor_action
    on admin_audit_events (actor_email, action);
