-- 비밀번호 재설정 링크 토큰(단발성). users 와는 email 문자열로 느슨히 연결한다.
create table if not exists password_reset_tokens (
    id bigint generated by default as identity,
    email varchar(255) not null,
    token varchar(255) not null,
    expires_at timestamp(6) with time zone not null,
    used boolean not null default false,
    created_at timestamp(6) with time zone not null,
    constraint pk_password_reset_tokens primary key (id)
);

create index if not exists idx_password_reset_tokens_token on password_reset_tokens (token);
create index if not exists idx_password_reset_tokens_email on password_reset_tokens (email);
