create table chat_rooms (
    id varchar(255) not null,
    name varchar(255) not null,
    description varchar(500),
    created_by varchar(255) not null,
    type varchar(255),
    direct_key varchar(512),
    created_at timestamp(6) with time zone not null,
    constraint pk_chat_rooms primary key (id),
    constraint uk_chat_rooms_direct_key unique (direct_key),
    constraint ck_chat_rooms_type check (type in ('GROUP', 'DIRECT'))
);

create table chat_room_participants (
    room_id varchar(255) not null,
    email varchar(255) not null,
    constraint fk_chat_room_participants_room foreign key (room_id) references chat_rooms (id)
);

create index idx_chat_room_participants_room
    on chat_room_participants (room_id);

create index idx_chat_room_participants_email
    on chat_room_participants (email);

create table chat_room_hidden_users (
    room_id varchar(255) not null,
    email varchar(255) not null,
    constraint fk_chat_room_hidden_users_room foreign key (room_id) references chat_rooms (id)
);

create index idx_chat_room_hidden_users_room
    on chat_room_hidden_users (room_id);

create index idx_chat_room_hidden_users_email
    on chat_room_hidden_users (email);

create table chat_room_read_states (
    id bigint generated by default as identity,
    room_id varchar(80) not null,
    user_email varchar(320) not null,
    last_read_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_chat_room_read_states primary key (id),
    constraint uk_chat_room_read_state_user unique (room_id, user_email)
);

create index idx_chat_room_read_state_room
    on chat_room_read_states (room_id);

create index idx_chat_room_read_state_user
    on chat_room_read_states (user_email);

create table chat_message_delivery_states (
    id bigint generated by default as identity,
    message_id varchar(80) not null,
    room_id varchar(80) not null,
    user_email varchar(320) not null,
    status varchar(20) not null,
    delivered_at timestamp(6) with time zone,
    read_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_chat_message_delivery_states primary key (id),
    constraint uk_chat_message_delivery_state_user unique (message_id, user_email),
    constraint ck_chat_message_delivery_status check (status in ('SENT', 'DELIVERED', 'READ'))
);

create index idx_chat_message_delivery_state_message
    on chat_message_delivery_states (message_id);

create index idx_chat_message_delivery_state_room_user
    on chat_message_delivery_states (room_id, user_email);

create index idx_chat_message_delivery_state_status
    on chat_message_delivery_states (status);

create table chat_room_user_preferences (
    id bigint generated by default as identity,
    room_id varchar(80) not null,
    user_email varchar(320) not null,
    pinned boolean not null,
    muted boolean not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_chat_room_user_preferences primary key (id),
    constraint uk_chat_room_user_preference unique (room_id, user_email)
);

create index idx_chat_room_user_preference_user
    on chat_room_user_preferences (user_email);

create index idx_chat_room_user_preference_room
    on chat_room_user_preferences (room_id);

create table notifications (
    id bigint generated by default as identity,
    recipient_email varchar(320) not null,
    actor_email varchar(320) not null,
    actor_name varchar(120) not null,
    type varchar(40) not null,
    title varchar(120) not null,
    body varchar(500) not null,
    target_room_id varchar(80),
    target_message_id varchar(80),
    created_at timestamp(6) with time zone not null,
    read_at timestamp(6) with time zone,
    constraint pk_notifications primary key (id),
    constraint ck_notifications_type check (type in ('CHAT_MESSAGE'))
);

create index idx_notifications_recipient_created
    on notifications (recipient_email, created_at);

create index idx_notifications_recipient_read
    on notifications (recipient_email, read_at);

create table push_device_tokens (
    id bigint generated by default as identity,
    user_email varchar(320) not null,
    token_hash varchar(64) not null,
    token varchar(4096) not null,
    platform varchar(20) not null,
    enabled boolean not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    last_seen_at timestamp(6) with time zone not null,
    constraint pk_push_device_tokens primary key (id),
    constraint uk_push_device_tokens_token_hash unique (token_hash),
    constraint ck_push_device_tokens_platform check (platform in ('WEB', 'ANDROID', 'IOS'))
);

create index idx_push_tokens_user_enabled
    on push_device_tokens (user_email, enabled);

create unique index idx_push_tokens_hash
    on push_device_tokens (token_hash);

create table outbox_events (
    id varchar(36) not null,
    aggregatetype varchar(120) not null,
    aggregateid varchar(120) not null,
    type varchar(160) not null,
    event_key varchar(200) not null,
    topic varchar(160) not null,
    payload text not null,
    timestamp timestamp(6) with time zone not null,
    status varchar(30) not null,
    attempts integer not null,
    next_attempt_at timestamp(6) with time zone not null,
    last_error varchar(2000),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    published_at timestamp(6) with time zone,
    constraint pk_outbox_events primary key (id),
    constraint ck_outbox_events_status check (status in ('PENDING', 'PUBLISHED', 'FAILED', 'DEAD'))
);

create index idx_outbox_events_status_next_attempt
    on outbox_events (status, next_attempt_at);

create index idx_outbox_events_aggregate
    on outbox_events (aggregatetype, aggregateid);

create index idx_outbox_events_created_at
    on outbox_events (created_at);
