-- 게임 개인 최고점수. (user_email, game)당 한 행. ddl-auto=validate이므로 GameScore 엔티티와 정확히 일치해야 한다.
create table game_scores (
    id bigint generated by default as identity,
    user_email varchar(320) not null,
    game varchar(20) not null,
    best_score integer not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_game_scores primary key (id),
    constraint uk_game_score_user_game unique (user_email, game),
    constraint ck_game_score_game check (game in ('SNAKE', 'TETRIS', 'G2048'))
);

create index idx_game_score_user
    on game_scores (user_email);
