-- 챗방 턴제 게임 대결. ddl-auto=validate이므로 GameMatch 엔티티와 정확히 일치해야 한다.
create table game_matches (
    id bigint generated by default as identity,
    room_id varchar(80) not null,
    game varchar(20) not null,
    challenger_email varchar(320) not null,
    challenger_name varchar(120) not null,
    challenger_score integer,
    opponent_email varchar(320),
    opponent_name varchar(120),
    opponent_score integer,
    status varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_game_matches primary key (id),
    constraint ck_game_match_game check (game in ('SNAKE', 'TETRIS', 'G2048')),
    constraint ck_game_match_status check (status in ('WAITING_CHALLENGER', 'WAITING_OPPONENT', 'DONE'))
);

create index idx_game_match_room
    on game_matches (room_id, created_at);
