-- 친구 요청/친구 관계. ACCEPTED 상태의 행이 곧 친구 관계(양방향 조회).
-- users 테이블은 auth-service 소유라 email 문자열로 느슨히 연결한다.
create table friend_requests (
    id bigint generated by default as identity,
    requester_email varchar(255) not null,
    addressee_email varchar(255) not null,
    status varchar(20) not null default 'PENDING',
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    constraint pk_friend_requests primary key (id),
    constraint uk_friend_requests_pair unique (requester_email, addressee_email)
);

create index idx_friend_requests_addressee on friend_requests (addressee_email, status);
create index idx_friend_requests_requester on friend_requests (requester_email, status);
